FROM ubuntu:21.04

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get install -y unzip && \
    apt-get install -y zip && \
    apt-get install -y openjdk-11-jdk && \
    apt-get install -y python3.9 && \
    apt-get install -y tar && \
    apt-get install -y wget && \
    apt-get install -y git && \
    apt-get install -y pip

ENV JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-arm64
#ENV JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64

#install Gradle
RUN curl -L http://downloads.gradle-dn.com/distributions/gradle-7.1.1-bin.zip -o /tmp/gradle.zip && \
    unzip -q /tmp/gradle.zip -d /opt && \
    rm -f /tmp/gradle.zip && \
    ln -s /opt/gradle-*/bin/gradle /usr/bin/

# Set Gradle in the environment variables
ENV GRADLE_HOME /opt/gradle-7.1.1
ENV PATH $PATH:/opt/gradle-7.1.1/bin

WORKDIR /root/gh-quality-analytics

COPY requirements.txt ./

RUN python3 -m pip install -r requirements.txt

COPY ./gradle_build_logs /root/gh-quality-analytics/gradle_build_logs
COPY ./auto_jacoco_gradle.py /root/gh-quality-analytics
COPY ./auto_jacoco_gradle.sh /root/gh-quality-analytics
COPY ./generate_build_data_from_gradle_logs.py /root/gh-quality-analytics

RUN ["chmod", "+x", "/root/gh-quality-analytics/auto_jacoco_gradle.sh"]

ENTRYPOINT ./auto_jacoco_gradle.sh
